name: Build and test

run-name:  Test build by @${{ github.actor }}

# Run the jobs for pushes and pull requests targetting main branch.
# NOTE: Strategy matrix can be mostly replaced with presets.
on: 
  push:
    branches:
      - CI

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    strategy:
      matrix:
        build:
          - 1
        include:
          - build: 1
            build-type: Release
            build-tests: 'ON'

    name: 'Ubuntu 20.04
      <type=${{ matrix.build-type }},
       tests=${{ matrix.build-tests }}>'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Maya SDK
        run: |
          cd $HOME/work
          curl -o devkit.tgz https://autodesk-adn-transfer.s3-us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2024/Autodesk_Maya_2024_2_Update_DEVKIT_Linux.tgz
      - name: Extract SDK Files
        run: |
          cd $HOME/work
          tar -xf devkit.tgz devkitBase/include devkitBase/lib
      - name: Create build directory
        run:
          mkdir .build
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -DMaya_SDK_ROOT_DIR=$HOME/work/devkitBase \
                ..
        working-directory: .build
      - name: Build
        run: |
          cmake --build . \
                --config ${{ matrix.build-type }} \
                --target test
        working-directory: .build
