name: Build and test

run-name: Test build by @${{ github.actor }}

on: 
  push:
    branches:
      - CI

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        build-type: [Release]
        maya-version: [2024.2, 2025]
        include:
            - maya-version: 2024.2
              devkit-url: https://autodesk-adn-transfer.s3-us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2024/Autodesk_Maya_2024_2_Update_DEVKIT_Linux.tgz
            - maya-version: 2025
              devkit-url: https://autodesk-adn-transfer.s3.us-west-2.amazonaws.com/ADN+Extranet/M%26E/Maya/devkit+2025/Autodesk_Maya_2025_DEVKIT_Linux.tgz

    name: 'Ubuntu <maya-version=${{ matrix.maya-version }}, build-type=${{ matrix.build-type }}>'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Maya SDK
        run: |
          cd $HOME/work
          curl -o devkit.tgz ${{ matrix.devkit-url }}
      - name: Extract SDK Files
        run: |
          cd $HOME/work
          tar -xf devkit.tgz devkitBase/include devkitBase/lib
      - name: Create build directory
        run:
          mkdir .build
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -DMaya_SDK_ROOT_DIR=$HOME/work/devkitBase \
                ..
        working-directory: .build
      - name: Build
        run: |
          cmake --build . \
                --config ${{ matrix.build-type }} \
                --verbose \
                --target test
        working-directory: .build
